version: '3.9'

services:
  memento:
    build: .
    volumes:
      - ./samples:/opt/memento/samples
      - ./cfg:/opt/memento/cfg
    image: rumblesan/memento-radio
  icecast:
    image: moul/icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=hackme
      - ICECAST_ADMIN_PASSWORD=hackme
      - ICECAST_PASSWORD=hackme
      - ICECAST_RELAY_PASSWORD=hackme
    ports:
      - "8000:8000"
